// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAShAOh4VANzP7PdSlGJLZOKYxWE0v58Vc',
    appId: '1:941018037259:web:2ec6851b9142d9077f5b0e',
    messagingSenderId: '941018037259',
    projectId: 'marwa-1942',
    authDomain: 'marwa-1942.firebaseapp.com',
    storageBucket: 'marwa-1942.firebasestorage.app',
    measurementId: 'G-9NPV94WNQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQP6sBRwCCukV1UB8GrQ8OkDhTOtymOcw',
    appId: '1:941018037259:android:fbc369f73bbf22697f5b0e',
    messagingSenderId: '941018037259',
    projectId: 'marwa-1942',
    storageBucket: 'marwa-1942.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIoQeUmxXV5drLppdIRQtpY7HECYoH1Jk',
    appId: '1:941018037259:ios:c3d9139261b78eb47f5b0e',
    messagingSenderId: '941018037259',
    projectId: 'marwa-1942',
    storageBucket: 'marwa-1942.firebasestorage.app',
    iosBundleId: 'com.example.pharmacyx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIoQeUmxXV5drLppdIRQtpY7HECYoH1Jk',
    appId: '1:941018037259:ios:c3d9139261b78eb47f5b0e',
    messagingSenderId: '941018037259',
    projectId: 'marwa-1942',
    storageBucket: 'marwa-1942.firebasestorage.app',
    iosBundleId: 'com.example.pharmacyx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAShAOh4VANzP7PdSlGJLZOKYxWE0v58Vc',
    appId: '1:941018037259:web:7278e9be748b66797f5b0e',
    messagingSenderId: '941018037259',
    projectId: 'marwa-1942',
    authDomain: 'marwa-1942.firebaseapp.com',
    storageBucket: 'marwa-1942.firebasestorage.app',
    measurementId: 'G-K7V7FPFMYZ',
  );
}
